### ISSUE TITLE
UA Query Explorer - TypeError: Cannot read properties of undefined (reading 'management')

### ISSUE THREAD

**Issue by thomas-bianconi-loreal-com** [googleanalytics/ga-dev-tools#1005]
**What page is this happening on**
https://ga-dev-tools.web.app/query-explorer/

**Describe the bug**
Impossible to use the application.
Authentification using google account works.
After granting permission the application get an error.

**To Reproduce**
1. Go to 'https://ga-dev-tools.web.app/query-explorer/'
2. Click on 'login'
3. Select a google account+
4. Click on 'Allow'
5. See error
`TypeError: Cannot read properties of undefined (reading 'management')
    at https://ga-dev-tools.web.app/a29ff5c541f9e539f1df2534bedd031b62257689-5e37438c8c72a3a26b26.js:1:10949
    at Object.useMemo (https://ga-dev-tools.web.app/framework-4ff4b9712e3100f7b5b1.js:2:65899)
    at t.useMemo (https://ga-dev-tools.web.app/framework-4ff4b9712e3100f7b5b1.js:2:125105)
    at v (https://ga-dev-tools.web.app/a29ff5c541f9e539f1df2534bedd031b62257689-5e37438c8c72a3a26b26.js:1:10895)
    at X (https://ga-dev-tools.web.app/component---src-pages-query-explorer-tsx-7c241927b08f0ba253b4.js:1:22020)
    at ro (https://ga-dev-tools.web.app/framework-4ff4b9712e3100f7b5b1.js:2:59976)
    at Hu (https://ga-dev-tools.web.app/framework-4ff4b9712e3100f7b5b1.js:2:112215)
    at Pi (https://ga-dev-tools.web.app/framework-4ff4b9712e3100f7b5b1.js:2:99421)
    at _i (https://ga-dev-tools.web.app/framework-4ff4b9712e3100f7b5b1.js:2:99349)
    at xi (https://ga-dev-tools.web.app/framework-4ff4b9712e3100f7b5b1.js:2:99212)`

**Expected behavior**
On step 5 expect to see the user interface to use the UA query explorer.

**Screenshots**
TypeError: Cannot read properties of undefined (reading 'management')
![image](https://user-images.githubusercontent.com/19604765/199958494-c208156d-7506-414e-b927-19ebbb53418f.png)

Using same browser, device with an other google account it seems to works : 
![image](https://user-images.githubusercontent.com/19604765/199958705-af5b46cb-c741-4df8-aff6-f09d8fe898a2.png)

**Comment by MCristofalo** [comment]
**bump** The problem persists
