### ISSUE TITLE
not able to run the project locally

### ISSUE THREAD

**Issue by arshad1tixsee** [googleanalytics/ga-dev-tools#219]
I also get error 

[18:50:57] Starting 'serve'...
[18:50:57] 'serve' errored after 21 ms
[18:50:57] **Error: spawn UNKNOWN
    at exports._errnoException (util.js:1026:11)
    at ChildProcess.spawn (internal/child_process.js:302:11)**

below is the log
0 info it worked if it ends with ok
1 verbose cli [ 'C:\Program Files\nodejs\node.exe',
1 verbose cli   'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.10.3
3 info using node@v6.4.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle ga-dev-tools@~prestart: ga-dev-tools@
6 silly lifecycle ga-dev-tools@~prestart: no script for prestart, continuing
7 info lifecycle ga-dev-tools@~start: ga-dev-tools@
8 verbose lifecycle ga-dev-tools@~start: unsafe-perm in lifecycle true
9 verbose lifecycle ga-dev-tools@~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;D:\tixsee\work\Embededfanxp\node_modules.bin;C:\Program Files\nodejs;c:\program files\graphicsmagick-1.3.24-q8;C:\Python27\;C:\Python27\Scripts;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Users\arshad.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Brackets\command;C:\Program Files (x86)\Skype\Phone\;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\MySQL\MySQL Fabric 1.5 & MySQL Utilities 1.5\;C:\Program Files (x86)\MySQL\MySQL Fabric 1.5 & MySQL Utilities 1.5\Doctrine extensions for PHP\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft Team Foundation Server 2015 Power Tools\;C:\Program Files\Git\cmd;C:\Program Files\MongoDB\Server\3.2\bin;C:\Program Files\TortoiseGit\bin;C:\Program Files\nodejs\;C:\Ruby200-x64\bin;C:\Users\arshad.dnx\bin;C:\Program Files\MongoDB\Server\3.2\bin;C:\Users\arshad\AppData\Roaming\npm;C:\Program Files (x86)\Google\google_appengine\
10 verbose lifecycle ga-dev-tools@~start: CWD: D:\tixsee\work\Embededfanxp
11 silly lifecycle ga-dev-tools@~start: Args: [ '/d /s /c', 'gulp watch' ]
12 silly lifecycle ga-dev-tools@~start: Returned: code: 1  signal: null
13 info lifecycle ga-dev-tools@~start: Failed to exec start script
14 verbose stack Error: ga-dev-tools@ start: `gulp watch`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:852:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid ga-dev-tools@
16 verbose cwd D:\tixsee\work\Embededfanxp
17 error Windows_NT 10.0.10586
18 error argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "start"
19 error node v6.4.0
20 error npm  v3.10.3
21 error code ELIFECYCLE
22 error ga-dev-tools@ start: `gulp watch`
22 error Exit status 1
23 error Failed at the ga-dev-tools@ start script 'gulp watch'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the ga-dev-tools package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     gulp watch
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs ga-dev-tools
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls ga-dev-tools
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by philipwalton** [comment]
Without knowing what steps you've taken prior to running that command, or what command you ran that produced that output, it's impossible to know what might have gone wrong.

**Comment by arshad1tixsee** [comment]
Hi,
Thanks for reply I ran npm start as per docs. Just tried to run the
solution without any editing

Regards,
Arshad

**Comment by philipwalton** [comment]
Did you run the other commands (like `pip install ...` and `npm install`)? Do you have GraphicsMagick installed on your system?

**Comment by philipwalton** [comment]
Also, I've never run the app on Windows, so I can't say for sure that it works. It's possible it doesn't.

**Comment by arshad1tixsee** [comment]
Hi,
Yes I hv installed the pre requisites and ran pip command.

Regards,
Arshad

**Comment by philipwalton** [comment]
I'm closing this due to inactivity, and I don't have any way to test it myself. If anyone else has any ideas, feel free to reopen.
