### ISSUE TITLE
Error: Cannot read property 'metadata' of undefined

### ISSUE THREAD

**Issue by scrumpto** [googleanalytics/ga-dev-tools#702]
Error Stack:

TypeError: Cannot read property 'metadata' of undefined
    at https://ga-dev-tools.web.app/component---src-pages-dimensions-metrics-explorer-tsx-f6c41461ab17bcc093a5.js:1:301152
    at Object.Co [as useMemo] (https://ga-dev-tools.web.app/framework-4ff4b9712e3100f7b5b1.js:2:64680)
    at t.useMemo (https://ga-dev-tools.web.app/framework-4ff4b9712e3100f7b5b1.js:2:125105)
    at ni (https://ga-dev-tools.web.app/component---src-pages-dimensions-metrics-explorer-tsx-f6c41461ab17bcc093a5.js:1:301098)
    at ri (https://ga-dev-tools.web.app/component---src-pages-dimensions-metrics-explorer-tsx-f6c41461ab17bcc093a5.js:1:303350)
    at ro (https://ga-dev-tools.web.app/framework-4ff4b9712e3100f7b5b1.js:2:59976)
    at Bo (https://ga-dev-tools.web.app/framework-4ff4b9712e3100f7b5b1.js:2:69494)
    at Hu (https://ga-dev-tools.web.app/framework-4ff4b9712e3100f7b5b1.js:2:113189)
    at Pi (https://ga-dev-tools.web.app/framework-4ff4b9712e3100f7b5b1.js:2:99421)
    at _i (https://ga-dev-tools.web.app/framework-4ff4b9712e3100f7b5b1.js:2:99349)

**Comment by diminishedprime** [comment]
Please recreate this bug, but use [this template](https://github.com/googleanalytics/ga-dev-tools/issues/new?assignees=&labels=&template=bug_report.md&title=)
