### ISSUE TITLE
Undefined metadata

### ISSUE THREAD

**Issue by Bzlbzlbzl** [googleanalytics/ga-dev-tools#717]
I am getting an error saying "Cannot read property 'metadata' of undefined" followed by "TypeError: Cannot read property 'metadata' of undefined
    at https://ga-dev-tools.web.app/component---src-pages-dimensions-metrics-explorer-tsx-0672c90b09d110f49aab.js:1:300735
    at Object.Co [as useMemo] (https://ga-dev-tools.web.app/framework-4ff4b9712e3100f7b5b1.js:2:64680)
    at t.useMemo (https://ga-dev-tools.web.app/framework-4ff4b9712e3100f7b5b1.js:2:125105)
    at ti (https://ga-dev-tools.web.app/component---src-pages-dimensions-metrics-explorer-tsx-0672c90b09d110f49aab.js:1:300681)
    at si (https://ga-dev-tools.web.app/component---src-pages-dimensions-metrics-explorer-tsx-0672c90b09d110f49aab.js:1:302799)
    at ro (https://ga-dev-tools.web.app/framework-4ff4b9712e3100f7b5b1.js:2:59976)
    at Bo (https://ga-dev-tools.web.app/framework-4ff4b9712e3100f7b5b1.js:2:69494)
    at Hu (https://ga-dev-tools.web.app/framework-4ff4b9712e3100f7b5b1.js:2:113189)
    at Pi (https://ga-dev-tools.web.app/framework-4ff4b9712e3100f7b5b1.js:2:99421)
    at _i (https://ga-dev-tools.web.app/framework-4ff4b9712e3100f7b5b1.js:2:99349)" when trying to access the UA Dimensions & Metrics Explorer

**Comment by diminishedprime** [comment]
Deployed a change that should prevent this error from happening in the future.
