### ISSUE TITLE
Cannot read properties of undefined (reading 'management')

### ISSUE THREAD

**Issue by Bzlbzlbzl** [googleanalytics/ga-dev-tools#721]
**What page is this happening on**
https://ga-dev-tools.web.app/account-explorer/

**Describe the bug**
The website displays an error message when loading the Account Explorer. Error message is:
"Something went wrong"
"Cannot read properties of undefined (reading 'management')"
"TypeError: Cannot read properties of undefined (reading 'management')
    at https://ga-dev-tools.web.app/0bac1b5cac5274bc351072e2775d17731edf9cf0-c686cfd4900068af941f.js:1:10387
    at Object.useMemo (https://ga-dev-tools.web.app/framework-4ff4b9712e3100f7b5b1.js:2:65899)
    at t.useMemo (https://ga-dev-tools.web.app/framework-4ff4b9712e3100f7b5b1.js:2:125105)
    at t.Z (https://ga-dev-tools.web.app/0bac1b5cac5274bc351072e2775d17731edf9cf0-c686cfd4900068af941f.js:1:10333)
    at t.Z (https://ga-dev-tools.web.app/0bac1b5cac5274bc351072e2775d17731edf9cf0-c686cfd4900068af941f.js:1:11634)
    at t.Z (https://ga-dev-tools.web.app/0bac1b5cac5274bc351072e2775d17731edf9cf0-c686cfd4900068af941f.js:1:9159)
    at D (https://ga-dev-tools.web.app/component---src-pages-account-explorer-tsx-1ae89f166d8543dd05c1.js:1:7100)
    at ro (https://ga-dev-tools.web.app/framework-4ff4b9712e3100f7b5b1.js:2:59976)
    at Hu (https://ga-dev-tools.web.app/framework-4ff4b9712e3100f7b5b1.js:2:112215)
    at Pi (https://ga-dev-tools.web.app/framework-4ff4b9712e3100f7b5b1.js:2:99421)"

**To Reproduce**
1. Click on "Account Explorer" tab to the left, or visit https://ga-dev-tools.web.app/account-explorer/
2. Log in to google account if not logged in already
3. See error

**Expected behavior**
What I expected to happen is to see an input field for my google analytics information, and search fields of some sort. 

**Screenshots**
![image](https://user-images.githubusercontent.com/54183435/132920076-1113218a-8da5-48f1-9b1d-34f868f701d5.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: Version 93.0.4577.63 (Official Build) (64-bit)

**Additional context**
"Reset App" button does not fix the problem

**Comment by diminishedprime** [comment]
This should be fixed in the latest version.
