### ISSUE TITLE
Cannot read properties of undefined (reading 'management') still an issue

### ISSUE THREAD

**Issue by molster** [googleanalytics/ga-dev-tools#745]
What page is this happening on
https://ga-dev-tools.web.app/account-explorer/

Describe the bug
The website displays an error message when loading the Account Explorer. Error message is:
"Something went wrong"
"Cannot read properties of undefined (reading 'management')"
TypeError: Cannot read properties of undefined (reading 'management')
    at https://ga-dev-tools.web.app/a29ff5c541f9e539f1df2534bedd031b62257689-fa61c6eda5b27d6ca493.js:1:15660
    at Object.useMemo (https://ga-dev-tools.web.app/framework-4ff4b9712e3100f7b5b1.js:2:65899)
    at t.useMemo (https://ga-dev-tools.web.app/framework-4ff4b9712e3100f7b5b1.js:2:125105)
    at v (https://ga-dev-tools.web.app/a29ff5c541f9e539f1df2534bedd031b62257689-fa61c6eda5b27d6ca493.js:1:15606)
    at K (https://ga-dev-tools.web.app/component---src-pages-query-explorer-tsx-4aad0afa4687d16e2ef0.js:1:12973)
    at ro (https://ga-dev-tools.web.app/framework-4ff4b9712e3100f7b5b1.js:2:59976)
    at Hu (https://ga-dev-tools.web.app/framework-4ff4b9712e3100f7b5b1.js:2:112215)
    at Pi (https://ga-dev-tools.web.app/framework-4ff4b9712e3100f7b5b1.js:2:99421)
    at _i (https://ga-dev-tools.web.app/framework-4ff4b9712e3100f7b5b1.js:2:99349)
    at xi (https://ga-dev-tools.web.app/framework-4ff4b9712e3100f7b5b1.js:2:99212)

To Reproduce

Click on "Account Explorer" tab to the left, or visit https://ga-dev-tools.web.app/account-explorer/
Log in to google account if not logged in already
See error
Expected behavior
What I expected to happen is to see an input field for my google analytics information, and search fields of some sort.

Desktop (please complete the following information):

OS: Windows 10
Browser: Google Chrome
Version: Version 93.0.4577.63 (Official Build) (64-bit)
Additional context
"Reset App" button does not fix the problem

**Comment by diminishedprime** [comment]
This is probably do to an extension blocking gapi from working correctly. Try disabling extensions and reload the page and see if you still have the issue.

**Comment by molster** [comment]
GitHub wouldn’t let me edit this - it was on the query explorer tool specifically - however it began working the day after I reported ( all Adblock tools were disabled)
