### ISSUE TITLE
Cannot read properties of undefined (reading 'management')

### ISSUE THREAD

**Issue by RuhanKnoetze** [googleanalytics/ga-dev-tools#754]
Getting the following error on this page 

https://ga-dev-tools.web.app/query-explorer/

Error : 
TypeError: Cannot read properties of undefined (reading 'management')
    at https://ga-dev-tools.web.app/a29ff5c541f9e539f1df2534bedd031b62257689-fa61c6eda5b27d6ca493.js:1:15660
    at Object.useMemo (https://ga-dev-tools.web.app/framework-4ff4b9712e3100f7b5b1.js:2:65899)
    at t.useMemo (https://ga-dev-tools.web.app/framework-4ff4b9712e3100f7b5b1.js:2:125105)
    at v (https://ga-dev-tools.web.app/a29ff5c541f9e539f1df2534bedd031b62257689-fa61c6eda5b27d6ca493.js:1:15606)
    at K (https://ga-dev-tools.web.app/component---src-pages-query-explorer-tsx-4aad0afa4687d16e2ef0.js:1:12973)
    at ro (https://ga-dev-tools.web.app/framework-4ff4b9712e3100f7b5b1.js:2:59976)
    at Hu (https://ga-dev-tools.web.app/framework-4ff4b9712e3100f7b5b1.js:2:112215)
    at Pi (https://ga-dev-tools.web.app/framework-4ff4b9712e3100f7b5b1.js:2:99421)
    at _i (https://ga-dev-tools.web.app/framework-4ff4b9712e3100f7b5b1.js:2:99349)
    at xi (https://ga-dev-tools.web.app/framework-4ff4b9712e3100f7b5b1.js:2:99212)

**Comment by paulkennethkent** [comment]
Hey @RuhanKnoetze, I just hit the same issue but solved it by disabling my `ublock origin` extension. Either your web browser or a certain extension on that web browser might be interfering with the query explorer.

**Comment by diminishedprime** [comment]
We were not able to reproduce this error.
