### ISSUE TITLE
UA Query Explorer not working

### ISSUE THREAD

**Issue by rptomey** [googleanalytics/ga-dev-tools#782]
Error: "Cannot read properties of undefined (reading 'management')"

Page: https://ga-dev-tools.web.app/query-explorer/

Error stack:
```
TypeError: Cannot read properties of undefined (reading 'management')
    at https://ga-dev-tools.web.app/a29ff5c541f9e539f1df2534bedd031b62257689-f1a950a984a8e95f9809.js:1:15880
    at Object.useMemo (https://ga-dev-tools.web.app/framework-4ff4b9712e3100f7b5b1.js:2:65899)
    at t.useMemo (https://ga-dev-tools.web.app/framework-4ff4b9712e3100f7b5b1.js:2:125105)
    at v (https://ga-dev-tools.web.app/a29ff5c541f9e539f1df2534bedd031b62257689-f1a950a984a8e95f9809.js:1:15826)
    at K (https://ga-dev-tools.web.app/component---src-pages-query-explorer-tsx-4aad0afa4687d16e2ef0.js:1:12973)
    at ro (https://ga-dev-tools.web.app/framework-4ff4b9712e3100f7b5b1.js:2:59976)
    at Hu (https://ga-dev-tools.web.app/framework-4ff4b9712e3100f7b5b1.js:2:112215)
    at Pi (https://ga-dev-tools.web.app/framework-4ff4b9712e3100f7b5b1.js:2:99421)
    at _i (https://ga-dev-tools.web.app/framework-4ff4b9712e3100f7b5b1.js:2:99349)
    at xi (https://ga-dev-tools.web.app/framework-4ff4b9712e3100f7b5b1.js:2:99212)
```

**Comment by diminishedprime** [comment]
This error is usually caused by an adblocker. Try turning off all extensions and reloading the page.
