### ISSUE TITLE
UA Query Explorer Bug

### ISSUE THREAD

**Issue by mars-globe** [googleanalytics/ga-dev-tools#793]
Can anyone help me on this issue I encountered when I went to UA Query Explorer? Thank you in advance!

>TypeError: Cannot read properties of undefined (reading 'management')
    at https://ga-dev-tools.web.app/a29ff5c541f9e539f1df2534bedd031b62257689-f1a950a984a8e95f9809.js:1:15880
    at Object.useMemo (https://ga-dev-tools.web.app/framework-4ff4b9712e3100f7b5b1.js:2:65899)
    at t.useMemo (https://ga-dev-tools.web.app/framework-4ff4b9712e3100f7b5b1.js:2:125105)
    at v (https://ga-dev-tools.web.app/a29ff5c541f9e539f1df2534bedd031b62257689-f1a950a984a8e95f9809.js:1:15826)
    at K (https://ga-dev-tools.web.app/component---src-pages-query-explorer-tsx-4aad0afa4687d16e2ef0.js:1:12973)
    at ro (https://ga-dev-tools.web.app/framework-4ff4b9712e3100f7b5b1.js:2:59976)
    at Hu (https://ga-dev-tools.web.app/framework-4ff4b9712e3100f7b5b1.js:2:112215)
    at Pi (https://ga-dev-tools.web.app/framework-4ff4b9712e3100f7b5b1.js:2:99421)
    at _i (https://ga-dev-tools.web.app/framework-4ff4b9712e3100f7b5b1.js:2:99349)
    at xi (https://ga-dev-tools.web.app/framework-4ff4b9712e3100f7b5b1.js:2:99212)

**Comment by dastoori** [comment]
@mars-globe I guess you're using an Ad Blocker. Try to disable it and refresh the page. It worked for me.
